- hosts: master
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_token
    
    - name: Copy join token to local file
      local_action: copy content="{{ join_token.stdout_lines[0] }}" dest=./join-token
      
- hosts: infra
  roles:
    - prereq
    - join

- hosts: master
  gather_facts: false
  tasks:
    - name: print cluster status
      shell: kubectl get nodes
      register: output
    - debug:
        var: output.stdout_lines      
