- name: pause for cluster to create all pods
  pause:
    minutes: 1

- name: Copy etcd files
  copy: src=./files/example.tar dest=./example.tar

- name: Untar 
  shell: tar -xvf ~/example.tar

- name: Copy install script
  copy: src=./files/etcd.sh dest=/tmp/etcd.sh mode=0755

- name: install Pod etcd
  command: sh /tmp/etcd.sh

- name: get pod details
  command: kubectl get po -n kube-system
