- name: copy /etc/hosts file
  copy:
    src: ./files/hosts
    dest: /etc/hosts
    mode: '0644'

- name: install centos-release-gluster
  yum:
    name: centos-release-gluster
    state: present
    update_cache: true

- name: stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: disable SELinux
  command: setenforce 0
  ignore_errors: yes

- name: disable SELinux on reboot
  selinux:
    state: disabled

- name: start glusterd
  service:
    name: glusterd
    state: started
    enabled: yes

- name: check peer san00
  shell: gluster peer probe san01
  register: gluster_san00
  when: {{ ansible_hostname }} is san00
- debug: 
    var: gluster_san00
  when: {{ ansible_hostname }} is san00
 
- name: check peer san01
  shell: gluster peer probe san00
  register: gluster_san01
  when: {{ ansible_hostname }} is san01
- debug:
    var: gluster_san01
  when: {{ ansible_hostname }} is san01



